version: "3.9"

services:
  netwatch-backend:
    build: ./backend
    container_name: netwatch-backend
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
    environment:
      - NETWATCH_DB_URL=postgresql+psycopg2://netwatch:netwatch123@postgres:5432/netwatch
    networks:
      - netwatch_internal
    volumes:
      - ./rules:/app/rules:ro

  netwatch-agent:
    build: ./agent
    container_name: netwatch-agent
    depends_on:
      - netwatch-backend
    environment:
      - NETWATCH_AGENT_ID=agent-lab-1
      - NETWATCH_API_URL=http://netwatch-backend:8000
      - NETWATCH_AGENT_MODE=mock   # or "proc"
    networks:
      - netwatch_internal

  netwatch-rules-worker:
    build: ./backend
    container_name: netwatch-rules-worker
    depends_on:
      - postgres
    environment:
      - NETWATCH_DB_URL=postgresql+psycopg2://netwatch:netwatch123@postgres:5432/netwatch
    networks:
      - netwatch_internal
    volumes:
      - ./rules:/app/rules:ro
    command: >
      sh -c "while true; do
               echo '[RULES] Running detection cycle...';
               python -m app.workers;
               sleep 60;
             done"      

  redis:
    image: redis:7-alpine
    container_name: netwatch-redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    networks:
      - netwatch_internal

  postgres:
    image: postgres:16-alpine
    container_name: netwatch-postgres
    environment:
      - POSTGRES_DB=netwatch
      - POSTGRES_USER=netwatch
      - POSTGRES_PASSWORD=netwatch123
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./infra/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - netwatch_internal

  grafana:
    image: grafana/grafana-oss:latest
    container_name: netwatch-grafana
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - netwatch_internal
    volumes:
      - ./infra/grafana/provisioning:/etc/grafana/provisioning

networks:
  netwatch_internal:
    driver: bridge

volumes:
  redis-data:
  postgres-data:
