
import { Outlet } from "react-router-dom";

import PageHeader from "@/shared/components/PageHeader";
import DetectionWorkflowRail from "@/shared/components/DetectionWorkflow";

export default function AlertsLayout() {
  return (
    <div className="space-y-6">
      <PageHeader
        title="Alerts"
        breadcrumb={["Detection"]}
        description="Alerts generated by YAML rules with portal-configurable overrides."
        tabs={[
          { label: "Queue", to: "/alerts/queue" },
          { label: "Rules", to: "/alerts/rules" }
        ]}
      />

      <DetectionWorkflowRail compact />

      <Outlet />
    </div>
  );
}
