apiVersion: 1

datasources:
  - name: Seagull Postgres
    type: postgres
    access: proxy
    orgId: 1
    uid: seagull-postgres
    isDefault: true
    url: postgres:5432
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      database: seagull
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400
      postgresVersion: 1400
      timescaledb: false

  - name: Seagull Elasticsearch
    type: elasticsearch
    access: proxy
    orgId: 1
    uid: seagull-elasticsearch
    isDefault: false
    url: http://elasticsearch:9200
    jsonData:
      index: 'seagull-events-*'
      timeField: '@timestamp'
      esVersion: 80
      interval: Daily
      maxConcurrentShardRequests: 5
